-- +goose Up 
CREATE TABLE feeds (
  ID UUID PRIMARY KEY,
  CREATED_AT TIMESTAMP NOT NULL, 
  UPDATED_AT TIMESTAMP NOT NULL, 
  URL TEXT NOT NULL, 
  USER_ID UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE feeds;
