-- +goose Up 
CREATE TABLE feeds (
  ID UUID NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL, 
  UPDATED_AT TIMESTAMP NOT NULL, 
  URL TEXT NOT NULL, 
  USER_ID UUID REFERENCES users(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE feeds;
